name: Cleanup All Artifacts

on:
  workflow_dispatch:
jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: Juice-Labs/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
